//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kal2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentDocument
    {
        public int ID { get; set; }
        public string DocumentType { get; set; }
        public System.DateTime AssignmentDate { get; set; }
        public Nullable<int> Equipment { get; set; }
    }
}
