//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kal2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentAreas = new HashSet<EquipmentArea>();
            this.EquipmentParameters = new HashSet<EquipmentParameter>();
            this.EquipmentDimensions = new HashSet<EquipmentDimension>();
        }
    
        public int ID { get; set; }
        public int EquipmentName { get; set; }
        public System.DateTime StartOperationDate { get; set; }
        public System.DateTime EndOperationDate { get; set; }
        public int EquipmentArea { get; set; }
        public int EquipmentParameter { get; set; }
    
        public virtual EquipmentName EquipmentName1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentArea> EquipmentAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentParameter> EquipmentParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentDimension> EquipmentDimensions { get; set; }
        public virtual EquipmentArea EquipmentArea1 { get; set; }
        public virtual EquipmentParameter EquipmentParameter1 { get; set; }
    }
}
