//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kal2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentDimension
    {
        public int ID { get; set; }
        public System.DateTime DimensionDate { get; set; }
        public int Employee { get; set; }
        public int Equipment { get; set; }
        public int Parameter { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Equipment Equipment1 { get; set; }
        public virtual Parameter Parameter1 { get; set; }
    }
}
